services:
  doc-ingestor:
    build:
      context: ./ingestor
      dockerfile: Dockerfile
    container_name: doc-ingestor
    volumes:
      - ./ingestor:/app
    environment:
    command: ["python", "extract_chunk_embed.py", "story.pdf"]
