name: Build and Push RAG-Lambda ingestor to AWS ECR

on:
  push:
    branches: [ main ]
    # paths:
    #   - 'ingestor/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::120569638976:role/GitHubActionsRole_summafyapp
          aws-region: ${{ secrets.AWS_ECR_REGION }}

      - name: Build Lambda package
        run: |
          cd ingestor
          chmod +x build_lambda_zip.sh
          ./build_lambda_zip.sh

      - name: Upload Lambda package to S3
        run: |
          aws s3 cp ./ingestor/lambda-ingestor.zip s3://${{ secrets.ZIP_BUCKET_NAME }}/lambda-ingestor.zip

      # - name: Login to Amazon ECR
      #   uses: aws-actions/amazon-ecr-login@v2

      # - name: Build Docker image
      #   run: |
      #     docker build -t ${{ secrets.AWS_ECR_INGESTOR }}:${{ github.sha }} ./ingestor

      # - name: Tag Docker image
      #   run: |
      #     docker tag ${{ secrets.AWS_ECR_INGESTOR }}:${{ github.sha }} ${{ secrets.AWS_ECR_INGESTOR }}:latest

      # - name: Push Docker image (git sha)
      #   run: |
      #     docker push ${{ secrets.AWS_ECR_INGESTOR }}:${{ github.sha }}

      # - name: Push Docker image (latest)
      #   run: |
      #     docker push ${{ secrets.AWS_ECR_INGESTOR }}:latest
      
      - name: Deploy to AWS Lambda
        run: |
          if aws cloudformation describe-stacks --stack-name summafy-lambdas > /dev/null 2>&1; then
            aws lambda update-function-code \
              --function-name summafy-lambdas-SummafyReadS3ContainerFunction-qBVFLZdIVR5f \
              --s3-bucket ${{ secrets.ZIP_BUCKET_NAME }} \
              --s3-key lambda-ingestor.zip
          fi
